//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnjiznicaProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knjiga
    {
        public Knjiga()
        {
            this.KorisnikKnjiga = new HashSet<KorisnikKnjiga>();
        }
    
        public int KnjigaID { get; set; }
        public string Naslov { get; set; }
        public string Autor { get; set; }
        public string ISBN { get; set; }
        public int BrojPrimjeraka { get; set; }
        public string Kategorija { get; set; }
        public bool Posudba { get; set; }
    
        public virtual ICollection<KorisnikKnjiga> KorisnikKnjiga { get; set; }
    }
}
