//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnjiznicaProjekt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnjiznicaEntities : DbContext
    {
        public KnjiznicaEntities()
            : base("name=KnjiznicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clan> Clan { get; set; }
        public DbSet<Knjiga> Knjiga { get; set; }
        public DbSet<KorisnikKnjiga> KorisnikKnjiga { get; set; }
        public DbSet<KorisnikRadionica> KorisnikRadionica { get; set; }
        public DbSet<Radionica> Radionica { get; set; }
        public DbSet<Zaposlenik> Zaposlenik { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
