//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnjiznicaProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.KorisnikKnjiga = new HashSet<KorisnikKnjiga>();
            this.KorisnikRadionica = new HashSet<KorisnikRadionica>();
        }
    
        public int KorisnikID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string OIB { get; set; }
        public string Adresa { get; set; }
        public System.DateTime DatumRodenja { get; set; }
        public string Email { get; set; }
        public string Spol { get; set; }
        public string StatusKorisnika { get; set; }
        public int BrojKnjiga { get; set; }
        public string BrojTelefona { get; set; }
        public int BrojIskaznice { get; set; }
        public string PIN { get; set; }
        public string KorisnickoIme { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual ICollection<KorisnikKnjiga> KorisnikKnjiga { get; set; }
        public virtual ICollection<KorisnikRadionica> KorisnikRadionica { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
