//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnjiznicaProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposlenik
    {
        public int KorisnikID { get; set; }
        public decimal Placa { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
